### ISSUE TITLE
Already fixed errors and crashes

### ISSUE THREAD

**Issue by luongcuong244** [ko2ic/image_downloader#151]
_Fixed error: 'when' expression must be exhaustive, add necessary 'is Pending', 'is Successful' branches or 'else' branch instead 
Fixed crash: android.database.CursorIndexOutOfBoundsException_

I was facing the errors when I downloaded multiple images in a row, but I have already fixed these errors.

Changed the way this library is imported
**from:**
```
  dependencies:
    image_downloader: ^0.31.0
```
**to:**
```
  dependencies:
    image_downloader:
      git:
        url: https://github.com/luongcuong244/image_downloader
```

Hope can help someone
